// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/transport/v1/message.proto

package transportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PING MessageType = 0 // 心跳检测
	MessageType_PONG MessageType = 1 // 心跳响应
	MessageType_DATA MessageType = 2 // 数据载荷
	MessageType_ACK  MessageType = 3 // 确认回执
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PING",
		1: "PONG",
		2: "DATA",
		3: "ACK",
	}
	MessageType_value = map[string]int32{
		"PING": 0,
		"PONG": 1,
		"DATA": 2,
		"ACK":  3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_transport_v1_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_api_transport_v1_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_api_transport_v1_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // UUID，全局唯一消息ID
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=transport.v1.MessageType" json:"type,omitempty"`                                                    // 消息类型
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // 实际数据载荷
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                        // 发送时间戳 (Unix Nano)
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据 (TraceID, Priority, etc.)
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                                         // Ed25519 签名，防篡改
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_transport_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_transport_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_transport_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PING
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_api_transport_v1_message_proto protoreflect.FileDescriptor

const file_api_transport_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/transport/v1/message.proto\x12\ftransport.v1\"\x9c\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.transport.v1.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.transport.v1.Message.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*4\n" +
	"\vMessageType\x12\b\n" +
	"\x04PING\x10\x00\x12\b\n" +
	"\x04PONG\x10\x01\x12\b\n" +
	"\x04DATA\x10\x02\x12\a\n" +
	"\x03ACK\x10\x03B:Z8github.com/omalloc/balefire/api/transport/v1;transportv1b\x06proto3"

var (
	file_api_transport_v1_message_proto_rawDescOnce sync.Once
	file_api_transport_v1_message_proto_rawDescData []byte
)

func file_api_transport_v1_message_proto_rawDescGZIP() []byte {
	file_api_transport_v1_message_proto_rawDescOnce.Do(func() {
		file_api_transport_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_transport_v1_message_proto_rawDesc), len(file_api_transport_v1_message_proto_rawDesc)))
	})
	return file_api_transport_v1_message_proto_rawDescData
}

var file_api_transport_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_transport_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_transport_v1_message_proto_goTypes = []any{
	(MessageType)(0), // 0: transport.v1.MessageType
	(*Message)(nil),  // 1: transport.v1.Message
	nil,              // 2: transport.v1.Message.MetadataEntry
}
var file_api_transport_v1_message_proto_depIdxs = []int32{
	0, // 0: transport.v1.Message.type:type_name -> transport.v1.MessageType
	2, // 1: transport.v1.Message.metadata:type_name -> transport.v1.Message.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_transport_v1_message_proto_init() }
func file_api_transport_v1_message_proto_init() {
	if File_api_transport_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_transport_v1_message_proto_rawDesc), len(file_api_transport_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_transport_v1_message_proto_goTypes,
		DependencyIndexes: file_api_transport_v1_message_proto_depIdxs,
		EnumInfos:         file_api_transport_v1_message_proto_enumTypes,
		MessageInfos:      file_api_transport_v1_message_proto_msgTypes,
	}.Build()
	File_api_transport_v1_message_proto = out.File
	file_api_transport_v1_message_proto_goTypes = nil
	file_api_transport_v1_message_proto_depIdxs = nil
}
